### ISSUE TITLE
Site.css not found

### ISSUE THREAD

**Issue by dmason511** [IdentityServer/IdentityServer3.AspNetIdentity#42]
I am trying to add some custom styling to this sample.
Tried adding the code as per documentation

var viewOptions = new DefaultViewServiceOptions();
viewOptions.Stylesheets.Add("/Content/Site.css");

var factory = new IdentityServerServiceFactory();
factory.ConfigureDefaultViewService(viewOptions);

when I step through the code "viewOptions" has it listed 
 idSvrFactory.ConfigureDefaultViewService(viewOptions);

I keep getting a 404 error.

Thanks

**Comment by brockallen** [comment]
Do you have a ~/content/site.css on your server? Also, I'd look at the rendered HTML to ensure the custom .css file is listed in the HTML.

**Comment by udayb2014** [comment]
So should a custom stylesheet have its own `<link>` entry in the html page?
