### ISSUE TITLE
Question: Remote Hosting

### ISSUE THREAD

**Issue by dotnetrules** [IdentityServer/IdentityServer3.AspNetIdentity#45]
Hi, with the recent updates to this project will it allow me to manage users on a remote server as well or will this still be limited to localhost only?

Thanks.

**Comment by brockallen** [comment]
IdentityServer does not manage users.

**Comment by dotnetrules** [comment]
Thanks @brockallen 

This project does allow you to use AspId EF persistence between IdSrv and IdMgr. Browsing to /admin it essentially brings up IdMgr where you can manage users. However can I please ask this question a different way in terms of best practices....

I am using AspId to share user data with IdMgr and IdSrv. I need to allow remote management of Users, their roles and claims, naturally using IdMgr.  Would it be a better practise to have a separate site just for IdMgr management (implementing remote host, owin configs, jwt etc) and have this authenticate against IdSrv hosted in another site so certain staff members can login into IdMgr  and do the whole user management thing?

Cheers :-D

**Comment by brockallen** [comment]
Ok, my terse answer was because perhaps your question is posted in the wrong repo. I think you want IdentityManager: https://github.com/IdentityManager/IdentityManager/

In short, you can configure proper authentication in IdMgr to allow non-localhost users.
