### ISSUE TITLE
How to customize IdentityUser

### ISSUE THREAD

**Issue by johnfake** [IdentityServer/IdentityServer3.AspNetIdentity#46]
Hi,

i'am using the AspNetIdentity Sample and it works so far (user is created).
Now I have tried to customize the User : IdentityUser with a new property "Group".

    public class User : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Group { get; set; }
    }

Now this message comes into play:
The model backing the 'Context' context has changed since the database was created. Consider using Code First Migrations to update the database

I know EF a little bit and added migrations to the project with this command:
Enable-Migrations -ContextTypeName SelfHost.AspId.CustomContext

In Migrations/Configuration.cs i've change AutomaticMigrationsEnabled = true.

Then: update-database results with:
There is already an object named 'AspNetRoles' in the database.

How can i change the users data?

Thanks for any hints !

**Comment by brockallen** [comment]
This is an EF issue, not an IdSvr issue. Check with Microsoft's support on how to handle this. But yes, I think you're on the right track with doing migrations.

**Comment by johnfake** [comment]
Seems that EF has problem with the two different context in the sample.
Removed one and it works now.
