### ISSUE TITLE
 An error occurred when trying to create a controller of type 'MetaController'. 

### ISSUE THREAD

**Issue by sudsy** [IdentityServer/IdentityServer3.AspNetIdentity#49]
First of all forgive me for my ignorance. It has been several years since working in Visual Studio and on .net and I have had a baptism (or is it a rebirthing) of fire in the past few days trying to do things that used to come so easily but are now very rusty.

I am sure you will look at these log files and know instantly what is wrong, but being as rusty as I am, I can't pinpoint my issue.

I have added IdentityManager to an asp.net webapi project and I am receiving the following error in the web based interface.

Error: An error occurred when trying to create a controller of type 'MetaController'. Make sure that the controller has a parameterless public constructor.

Sadly, when I enable tracing the log isn't much more help to me.

I have pasted the log file here http://pastebin.com/SdwctvRs

Anything you could do to point me in the right direction would be helpful.

Best Regards,

Ben

**Comment by brockallen** [comment]
Yea, I think this was a version mismatch issue when you upgrade to MR 8.4. You also need to upgrade your IdMgr to beta5-5 of IdMgr and beta5-1 IdMgr.MR.

**Comment by sudsy** [comment]
Sorry, Realised this is posted in the wrong repo. Please see this new issue:

I have attempted to diagnose the issue further based on your feedback.

https://github.com/IdentityManager/IdentityManager.AspNetIdentity/issues/22
