### ISSUE TITLE
[Question] AspNetIdentity and Asp.net vnext

### ISSUE THREAD

**Issue by angelcalvasp** [IdentityServer/IdentityServer3.AspNetIdentity#52]
Hello there, Is this supported yet? if it is how is it implemented Im kinda lost here, just starting out

**Comment by brockallen** [comment]
There's a NuGet from this repo: https://github.com/IdentityServer/IdentityServer3.AspNetIdentity

**Comment by angelcalvasp** [comment]
I added the NuGet Reference but couldn't use it for some reason, there must be something different.

**Comment by brockallen** [comment]
Yea, I don't expect the NuGet to work -- our NuGet is for AspId 2 (not 3 which requires DNX).

**Comment by angelcalvasp** [comment]
I will close this since I'm gonna go back to the non Beta Asp.Net
