### ISSUE TITLE
UserService not update userinfo when database changed

### ISSUE THREAD

**Issue by khoainv** [IdentityServer/IdentityServer3.AspNetIdentity#57]
I have 2 system:
1. IdentityServer3 using AspNetIdentity
2. IdentityManager

I login IdentityManager and change password => view on database it have changed. But login by IdentityServer3 then password is old and not change with new password.

I don't understand IdentityServer3 with AspNetIdentity using cache how?
In class AspNetIdentityUserService debug to method AuthenticateLocalAsync call FindUserAsync(username) is running to database, But I view result of method FindUserAsync(username) then UserInfo <> UserInfo on Database?

Can you have me?

**Comment by brockallen** [comment]
Make sure you are not caching your DbContext on the IdSvr side.

**Comment by khoainv** [comment]
I using:

 public static void ConfigureUserService(this IdentityServerServiceFactory factory, ApplicationDbContext dbContext)
        {
            factory.UserService = new Registration<IUserService, UserService>();
            //factory.ClaimsProvider = new Registration<IClaimsProvider, AscendClaimsProvider>();
            factory.Register(new Registration<ApplicationUserManager>());
            factory.Register(new Registration<ApplicationDbContext>(dbContext));
        }

**Comment by brockallen** [comment]
Not sure then -- you'll have to debug some more.

**Comment by khoainv** [comment]
I fixed by after solution:
public static void ConfigureUserService(this IdentityServerServiceFactory factory)
        {
            factory.UserService = new Registration&lt;IUserService, UserService&gt;();
            //factory.ClaimsProvider = new Registration&lt;IClaimsProvider, AscendClaimsProvider&gt;();
            factory.Register(new Registration&lt;ApplicationUserManager&gt;());

            //factory.Register(new Registration&lt;ApplicationDbContext&gt;(new ApplicationDbContext()));
            //DBContext not Caching, Fix bug DB Changed =&gt; IdSrv not change
            factory.Register(new Registration&lt;ApplicationDbContext&gt;(resolver =&gt; new ApplicationDbContext()));
        }
