### ISSUE TITLE
"MetaController" error with IdentityServer3.AspNetIdentity version="2.0.0"

### ISSUE THREAD

**Issue by aseemflowingly** [IdentityServer/IdentityServer3.AspNetIdentity#59]
I have hosted Identity Server 3 in an ASP.net MVC (4.5.2) app with following packages:

    <packages>
    <package id="Antlr" version="3.4.1.9004" targetFramework="net452" />
    <package id="bootstrap" version="3.0.0" targetFramework="net452" />
    <package id="EntityFramework" version="6.1.3" targetFramework="net452" />
    <package id="IdentityManager" version="1.0.0-beta5-5" targetFramework="net452" />
    <package id="IdentityManager.AspNetIdentity" version="1.0.0-beta5-1" targetFramework="net452"   />
    <package id="IdentityModel" version="1.0.0" targetFramework="net452" />
    <package id="IdentityServer3" version="2.3.0" targetFramework="net452" />
    <package id="IdentityServer3.AspNetIdentity" version="2.0.0" targetFramework="net452" />
    <package id="jQuery" version="1.10.2" targetFramework="net452" />
    <package id="jQuery.Validation" version="1.11.1" targetFramework="net452" />
    <package id="Microsoft.AspNet.Identity.Core" version="2.2.1" targetFramework="net452" />
    <package id="Microsoft.AspNet.Identity.EntityFramework" version="2.2.1" targetFramework="net452" />
    <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net452" />
    <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net452" />
    <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net452" />
    <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net452" />
    <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.0" targetFramework="net452" />
    <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net452"  />
    <package id="Microsoft.Net.Compilers" version="1.0.0" targetFramework="net452" developmentDependency="true" />
    <package id="Microsoft.Owin" version="3.0.1" targetFramework="net452" />
    <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net452" />
    <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net452" />
    <package id="Modernizr" version="2.6.2" targetFramework="net452" />
    <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net452" />
    <package id="Owin" version="1.0" targetFramework="net452" />
    <package id="Respond" version="1.2.0" targetFramework="net452" />
    <package id="Thinktecture.IdentityServer3" version="1.6.3" targetFramework="net452" />
    <package id="WebGrease" version="1.5.2" targetFramework="net452" />
    </packages>
    
And I am using EntityFramework with connection to SQL server Db to store the ASP.net Identity tables.

I end up getting the following error:

![image](https://cloud.githubusercontent.com/assets/16090447/12153509/0e66fa8e-b51f-11e5-91e1-f2752aebb7fa.png)

The AspNetIdentity & AspNetIdentity_2fa samples work, but they make use of older versions:

AspNetIdentity_2fa sample:

    <package id="IdentityServer3" version="2.0.0" targetFramework="net45" />
    <package id="IdentityServer3.AspNetIdentity" version="2.0.0-build00024" targetFramework="net45" />

ASPNetIdentity sample:

    <package id="IdentityServer3" version="2.0.0-build00174" targetFramework="net45" />
    <package id="IdentityServer3.AspNetIdentity" version="2.0.0-build00036" targetFramework="net45" />

**Comment by aseemflowingly** [comment]
Not sure if this is related, but I get following error logged when I try to get a token from the Identity Server 

   client.RequestResourceOwnerPasswordAsync("user", "password").Result;

when the client setup as 

    ClientId = "flowinglyportal",  Enabled = true,
    Flow = Flows.ResourceOwner,
    AccessTokenType = AccessTokenType.Reference,
    AllowAccessToAllScopes = true,

The error log is

    <Data Name="Buffer">{&quot;Message&quot;:&quot;An error has occurred.&quot;,&quot;ExceptionMessage&quot;:&quot;An error occurred when trying to create a controller of type &apos;TokenEndpointController&apos;. Make sure that the controller has a parameterless public constructor.&quot;,&quot;ExceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;StackTrace&quot;:&quot;   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.&lt;SendAsync&gt;d__1.MoveNext() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0&quot;,&quot;InnerException&quot;:{&quot;Message&quot;:&quot;An error has occurred.&quot;,&quot;ExceptionMessage&quot;:&quot;None of the constructors found with &apos;Autofac.Core.Activators.Reflection.DefaultConstructorFinder&apos; on type &apos;IdmDemo.Models.ApplicationUserManager&apos; can be invoked with the available services and parameters:\r\nCannot resolve parameter &apos;Microsoft.AspNet.Identity.IUserStore`1[IdmDemo.Models.FlowinglyUser] store&apos; of constructor &apos;Void .ctor(Microsoft.AspNet.Identity.IUserStore`1[IdmDemo.Models.FlowinglyUser])&apos;.&quot;,&quot;ExceptionType&quot;:&quot;Autofac.Core.DependencyResolutionException&quot;,&quot;StackTrace&quot;:&quot;   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.&lt;&gt;c__DisplayClass8.&lt;RegistrationsFor&gt;b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.AutowiringParameter.&lt;&gt;c__DisplayClass2.&lt;CanSupplyValue&gt;b__0() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.&lt;&gt;c__DisplayClass8.&lt;RegistrationsFor&gt;b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object&amp; instance) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.ResolvedParameter.&lt;&gt;c__DisplayClass6`1.&lt;ForKeyed&gt;b__5(ParameterInfo pi, IComponentContext c) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at Autofac.Core.ResolvedParameter.&lt;&gt;c__DisplayClass2.&lt;CanSupplyValue&gt;b__0() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 pTRUNCATED...</Data>
   
and subsequent log as:

    <Data Name="Buffer">ibute.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.AutowiringParameter.&lt;&gt;c__DisplayClass2.&lt;CanSupplyValue&gt;b__0() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Registration.ExternalRegistrySource.&lt;&gt;c__DisplayClass8.&lt;RegistrationsFor&gt;b__3(IComponentContext c, IEnumerable`1 p) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object&amp; instance) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at Autofac.Integration.WebApi.AutofacWebApiDependencyScope.GetService(Type serviceType) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\ClaimMap.cs:line 0\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1&amp; activator) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\\local\\identity\\server3\\Core\\source\\Core\\Configuration\\Hosting\\PreventUnsupportedRequestMediaTypesAttribute.cs:line 0&quot;}}</Data>

**Comment by brockallen** [comment]
I can't tell anything from those logs -- does anything stand out to you? Normally you'd see something like "DB Connection failed" for example.

**Comment by aseemflowingly** [comment]
I searched for logs for anything related to "db', came up with nothing.

I thought it might be related to the error related to "meta controller" ? I still get that if I navigate to "admin" using a browser.

**Comment by brockallen** [comment]
Yea, try browsing to ~/admin/api and see if there's anything else in the error.

**Comment by aseemflowingly** [comment]
I get this:

    {"message":"An error has occurred.","exceptionMessage":"An error occurred when trying to create a controller of type 'MetaController'. 
    Make sure that the controller has a parameterless public constructor.","exceptionType":"System.InvalidOperationException","stackTrace":"   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0","innerException":{"message":"An error has occurred.","exceptionMessage":"

    None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'IdmDemo.Models.ApplicationUserManager' can be invoked with the available services and parameters:\r\nCannot resolve parameter 'Microsoft.AspNet.Identity.IUserStore`1[IdmDemo.Models.FlowinglyUser] store' of constructor 'Void .ctor(Microsoft.AspNet.Identity.IUserStore`1[IdmDemo.Models.FlowinglyUser])'.","exceptionType":"Autofac.Core.DependencyResolutionException","stackTrace":"   at 

    Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at  

    Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

     Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 

    Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at 
    Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at IdentityManager.Configuration.Hosting.AutofacScope.GetService(Type serviceType) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Configuration\\Hosting\\AutofacScope.cs:line 36\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\\ballen\\github\\identity\\IdMgr\\IdentityManager\\source\\Core\\Logging\\TraceSourceLogProvider.cs:line 0"}}

Does this help?

**Comment by brockallen** [comment]
My DB error comment before was because sometimes when you have a DB error, the DbContext can't be created, and thus the error looks like a DI error. Since this really does seem more like a DI error, especially due to the `IUserStore<FlowinglyUser>`. I have a feeling the IdMgr DI is just not properly configured. 

I'd compare your DI config to the working sample.

**Comment by aseemflowingly** [comment]
Cool! I got the issue, the UserManager was setup wrong. I changed that and the meta controller error is gone!
@brockallen Thanks for the help! :+1:
