### ISSUE TITLE
Is it working with new ASP.NET 5?

### ISSUE THREAD

**Issue by yrikturash** [IdentityServer/IdentityServer3.AspNetIdentity#61]
I have to use Identity Server 3 in ASP.NET 5 with Asp Identity. Is it possible to use this nuget? Or there is other approaches? Thanks

**Comment by brockallen** [comment]
This repo only provides a lightweight base implementation of the IUserService. If you're using ASP.NET Identity 3, then I suggest implementing your own IUserService.
