### ISSUE TITLE
Dependency on IdentityManager, which is ASP.NET MVC UI application

### ISSUE THREAD

**Issue by dmitrynovik** [IdentityServer/IdentityServer3.AspNetIdentity#62]
The funny thing: this code depends on identitymanager, which is ASP.NET MVC web application. I'd rather expect reverse. 

The IdentityManager probably needs a split - UI separately from Core logic, so one can have AspNet Identity Model without running ASP.NET MVC UI

**Comment by brockallen** [comment]
I don't follow -- the host references IdentityManager, but the core does not.

**Comment by dmitrynovik** [comment]
My bad, I've confused it with IdentityManager.AspNetIdentity.

**Comment by brockallen** [comment]
So then is there still an issue, or can we close this?

**Comment by dmitrynovik** [comment]
PLease close.
