### ISSUE TITLE
nuget package unlisted

### ISSUE THREAD

**Issue by raxitr** [IdentityServer/IdentityServer3.AspNetIdentity#65]
I am trying to install Thinktecture.IdentityServer3.AspNetIdentity from nuget but the warning says the nuget package has been unlisted. What could be the reason should I be using something else? 

I am using Identity server 1.6.3 is that a latest version?

**Comment by leastprivilege** [comment]
https://www.nuget.org/profiles/identity

**Comment by raxitr** [comment]
:+1:  Got it. thanks
