### ISSUE TITLE
AspNetUserRoles Not Used

### ISSUE THREAD

**Issue by BruceHunter** [IdentityServer/IdentityServer3.AspNetIdentity#66]
I noticed that when using IdentityServer3.AspNetIdentity along with IdentityManager that the Roles get put in AspNetUserClaims instead of the table AspNetUserRoles. 

What is the reason for this?
I know we should be using claims more.

**Comment by brockallen** [comment]
Because roles are just claims.

**Comment by BruceHunter** [comment]
I figured that and of course agree with your statement. I just hate having a table that isn't used at all. I wonder if I can delete it without having issues. Darn it M$.

**Comment by BruceHunter** [comment]
I am going to close this.
