### ISSUE TITLE
IdentityServer3.AspNetIdentity vs IdentityManager.AspNetIdentity

### ISSUE THREAD

**Issue by BruceHunter** [IdentityServer/IdentityServer3.AspNetIdentity#67]
I understand that IdentityServer3.AspNetIdentity only uses the UserManager class.
I understand that IdentityManager.AspNetIdentity uses UserManager and RoleManager.

I also understand that we inherit your classes and pass into register. These are service classes in my code, hooking to the same AspNet Identity tables. 

I have a lower layer where both these classes reside. To me this is duplicate functionality.

I do not want to create my own UserService to build in additional functionality. I want to extend and add methods to a class that's already wrapping the UserManager. The same goes for the RoleManager. The question is, which Service class to extend.

Another reason to extend the Service classes we have to create is so that we are inline with IdentityServer and IdentityManager. (How you are doing Roles as only claims is one example).

If there is anyway to bring these 2 together and still get the goal you want. To me that makes more sense.

Otherwise, I'm going to have to recreate a lot of what you did in your 2 service classes in my own service class with UserManager and RoleManager and try to be inline with how your doing things.

**Comment by brockallen** [comment]
> I have a lower layer where both these classes reside. To me this is duplicate functionality.

Yep, and the real issue is that OWIN/Katana does not standardize on a DI system. Also, then for IdSvr and IdMgr they don't want to make assumptions about other moving parts that may or may not be in your host. 

It'll all be better in ASP.NET Core :)
