### ISSUE TITLE
using identity reboot with identity server

### ISSUE THREAD

**Issue by SeanFarrow** [IdentityServer/IdentityServer3.AspNetIdentity#73]
Hui,

Since Identity reboot derives from asp.net identity, what is the best/easiest way of using this with Identity server?
Kind regards
Sean.

**Comment by brockallen** [comment]
Just use the regular ASP.NET Identity and plug in IR where it normally gets plugged in.

**Comment by SeanFarrow** [comment]
Thanks. Is there integration for identity manager/managing users from identity servers ui?
Cheers
Sean.

**Comment by brockallen** [comment]
No, that's no IdSvr's job. You can always use IdentityManager, but it's technically separate.

**Comment by SeanFarrow** [comment]
So, do I need to plugin ir in to identity server. I'm thinking due to the adaptive password hashing/2fa stuff, or does it just go in to the app.
Confused!
Cheers
SEan.

**Comment by brockallen** [comment]
IR just provides a replacement for the hashing API -- that's it. The rest is mainly the same as ASP.NET Identity.
